"""Add event_key to notifications

Revision ID: 06e62c2d30d8
Revises: 021dab782c36
Create Date: 2026-02-21 11:51:46.310009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e62c2d30d8'
down_revision: Union[str, Sequence[str], None] = '021dab782c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('event_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_notifications_event_key'), 'notifications', ['event_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_event_key'), table_name='notifications')
    op.drop_column('notifications', 'event_key')
    # ### end Alembic commands ###
