"""add_teacher_feedback

Revision ID: 07ad11f98eb6
Revises: 9d1731e428c0
Create Date: 2026-03-19 08:16:11.627821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ad11f98eb6'
down_revision: Union[str, Sequence[str], None] = '9d1731e428c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'activity_logs', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'signup_requests', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.add_column('student_assignments', sa.Column('teacher_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_assignments', 'teacher_feedback')
    op.drop_constraint(None, 'signup_requests', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    # ### end Alembic commands ###
