"""add_student_answer_options_table

Revision ID: 180818ee4335
Revises: 07ad11f98eb6
Create Date: 2026-03-20 14:37:52.296935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180818ee4335'
down_revision: Union[str, Sequence[str], None] = '07ad11f98eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_answer_options',
    sa.Column('student_answer_id', sa.Integer(), nullable=False),
    sa.Column('mcq_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mcq_option_id'], ['mcq_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_answer_id'], ['student_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_answer_id', 'mcq_option_id')
    )
    op.drop_constraint(op.f('student_answers_selected_option_id_fkey'), 'student_answers', type_='foreignkey')
    op.drop_column('student_answers', 'selected_option_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_answers', sa.Column('selected_option_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('student_answers_selected_option_id_fkey'), 'student_answers', 'mcq_options', ['selected_option_id'], ['id'])
    op.drop_table('student_answer_options')
    # ### end Alembic commands ###
