"""add_course_id_to_activity_log

Revision ID: 1a458e7abbc3
Revises: 2610063eda9e
Create Date: 2026-03-03 22:27:50.100318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a458e7abbc3'
down_revision: Union[str, Sequence[str], None] = '2610063eda9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_activity_logs_course_id'), 'activity_logs', ['course_id'], unique=False)
    op.create_foreign_key(None, 'activity_logs', 'course', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_index(op.f('ix_activity_logs_course_id'), table_name='activity_logs')
    op.drop_column('activity_logs', 'course_id')
    # ### end Alembic commands ###
