"""Update assignment reference materials to JSONB

Revision ID: 1f1bc34cc907
Revises: 237b1cccbf17
Create Date: 2026-03-06 13:05:36.231648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f1bc34cc907'
down_revision: Union[str, Sequence[str], None] = '237b1cccbf17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('reference_materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('assignments', 'reference_material_url')
    op.drop_column('assignments', 'reference_material_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('reference_material_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assignments', sa.Column('reference_material_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('assignments', 'reference_materials')
    # ### end Alembic commands ###
