"""Add reference material columns to assignments

Revision ID: 237b1cccbf17
Revises: 1a458e7abbc3
Create Date: 2026-03-05 13:04:24.703230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237b1cccbf17'
down_revision: Union[str, Sequence[str], None] = '1a458e7abbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE assignments ADD COLUMN IF NOT EXISTS reference_material_url VARCHAR")
    op.execute("ALTER TABLE assignments ADD COLUMN IF NOT EXISTS reference_material_name VARCHAR")
    op.execute("ALTER TABLE questions ADD COLUMN IF NOT EXISTS order_index INTEGER DEFAULT 0 NOT NULL")
    
    op.execute("ALTER TABLE questions ALTER COLUMN order_index SET NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('assignments', 'reference_material_name')
    op.drop_column('assignments', 'reference_material_url')
    # ### end Alembic commands ###
