"""add_file_records_table

Revision ID: 2610063eda9e
Revises: 674e141238dc
Create Date: 2026-02-26 18:16:43.588897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2610063eda9e'
down_revision: Union[str, Sequence[str], None] = '674e141238dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_name', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_records_object_name'), 'file_records', ['object_name'], unique=True)
    op.create_index(op.f('ix_file_records_school_id'), 'file_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_file_records_uploaded_by'), 'file_records', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_records_uploaded_by'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_school_id'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_object_name'), table_name='file_records')
    op.drop_table('file_records')
    # ### end Alembic commands ###
