"""add_multi_tenancy_school_isolation_final

Revision ID: 42853ae5ee0e
Revises: 579436368d5b
Create Date: 2026-02-26 14:28:40.996927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42853ae5ee0e'
down_revision: Union[str, Sequence[str], None] = '579436368d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Update schools table - add columns as nullable first
    op.add_column('schools', sa.Column('subscription_start', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('schools', sa.Column('subscription_end', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('schools', sa.Column('max_teachers', sa.Integer(), nullable=True))
    
    # Populate existing schools with defaults
    op.execute("UPDATE schools SET subscription_start = now() WHERE subscription_start IS NULL")
    op.execute("UPDATE schools SET subscription_end = now() + interval '1 year' WHERE subscription_end IS NULL")
    op.execute("UPDATE schools SET max_teachers = 10 WHERE max_teachers IS NULL")
    
    # Now make them non-nullable
    op.alter_column('schools', 'subscription_start', nullable=False)
    op.alter_column('schools', 'subscription_end', nullable=False)
    op.alter_column('schools', 'max_teachers', nullable=False)
    
    op.drop_index(op.f('ix_schools_slug'), table_name='schools')
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=True)
    op.drop_column('schools', 'slug')
    op.drop_column('schools', 'is_active')

    # 2. Update enrollment tables - add school_id as nullable first
    op.add_column('student_course', sa.Column('school_id', sa.Integer(), nullable=True))
    op.add_column('teacher_course', sa.Column('school_id', sa.Integer(), nullable=True))
    
    # Populate with default school (id=1)
    op.execute("UPDATE student_course SET school_id = 1 WHERE school_id IS NULL")
    op.execute("UPDATE teacher_course SET school_id = 1 WHERE school_id IS NULL")
    
    # Now make non-nullable and add index/FK
    op.alter_column('student_course', 'school_id', nullable=False)
    op.create_index(op.f('ix_student_course_school_id'), 'student_course', ['school_id'], unique=False)
    op.create_foreign_key(None, 'student_course', 'schools', ['school_id'], ['id'])
    
    op.alter_column('teacher_course', 'school_id', nullable=False)
    op.create_index(op.f('ix_teacher_course_school_id'), 'teacher_course', ['school_id'], unique=False)
    op.create_foreign_key(None, 'teacher_course', 'schools', ['school_id'], ['id'])

    # 3. Handle other existing school_id columns
    op.create_index(op.f('ix_activity_logs_school_id'), 'activity_logs', ['school_id'], unique=False)
    
    op.alter_column('course', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_course_school_id'), 'course', ['school_id'], unique=False)
    op.drop_constraint(op.f('course_school_id_fkey'), 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'schools', ['school_id'], ['id'])
    
    op.alter_column('learning_material', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_learning_material_school_id'), 'learning_material', ['school_id'], unique=False)
    op.drop_constraint(op.f('learning_material_school_id_fkey'), 'learning_material', type_='foreignkey')
    op.create_foreign_key(None, 'learning_material', 'schools', ['school_id'], ['id'])
    
    op.create_index(op.f('ix_notifications_school_id'), 'notifications', ['school_id'], unique=False)
    op.create_index(op.f('ix_signup_requests_school_id'), 'signup_requests', ['school_id'], unique=False)
    
    op.alter_column('submissions', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_submissions_school_id'), 'submissions', ['school_id'], unique=False)
    op.drop_constraint(op.f('submissions_school_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'schools', ['school_id'], ['id'])
    
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.drop_constraint(op.f('users_school_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_school_id_fkey'), 'users', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_constraint(None, 'teacher_course', type_='foreignkey')
    op.drop_index(op.f('ix_teacher_course_school_id'), table_name='teacher_course')
    op.drop_column('teacher_course', 'school_id')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_school_id_fkey'), 'submissions', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_submissions_school_id'), table_name='submissions')
    op.alter_column('submissions', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'student_course', type_='foreignkey')
    op.drop_index(op.f('ix_student_course_school_id'), table_name='student_course')
    op.drop_column('student_course', 'school_id')
    op.drop_index(op.f('ix_signup_requests_school_id'), table_name='signup_requests')
    op.add_column('schools', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('schools', sa.Column('slug', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.create_index(op.f('ix_schools_slug'), 'schools', ['slug'], unique=True)
    op.drop_column('schools', 'max_teachers')
    op.drop_column('schools', 'subscription_end')
    op.drop_column('schools', 'subscription_start')
    op.drop_index(op.f('ix_notifications_school_id'), table_name='notifications')
    op.drop_constraint(None, 'learning_material', type_='foreignkey')
    op.create_foreign_key(op.f('learning_material_school_id_fkey'), 'learning_material', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_learning_material_school_id'), table_name='learning_material')
    op.alter_column('learning_material', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key(op.f('course_school_id_fkey'), 'course', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_course_school_id'), table_name='course')
    op.alter_column('course', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_activity_logs_school_id'), table_name='activity_logs')
    # ### end Alembic commands ###
