"""Add principal to signup roles

Revision ID: 579436368d5b
Revises: cb82c48ca97d
Create Date: 2026-02-24 18:01:10.801418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579436368d5b'
down_revision: Union[str, Sequence[str], None] = 'cb82c48ca97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE signup_requested_role ADD VALUE IF NOT EXISTS 'principal'")
    op.execute("ALTER TYPE signup_approved_role ADD VALUE IF NOT EXISTS 'principal'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL does not easily support removing enum values
    pass
    # ### end Alembic commands ###
