"""add_school_id_to_password_change_requests

Revision ID: 674e141238dc
Revises: 42853ae5ee0e
Create Date: 2026-02-26 18:05:08.470155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674e141238dc'
down_revision: Union[str, Sequence[str], None] = '42853ae5ee0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_change_requests', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_password_change_requests_school_id'), 'password_change_requests', ['school_id'], unique=False)
    op.create_foreign_key(None, 'password_change_requests', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_change_requests', type_='foreignkey')
    op.drop_index(op.f('ix_password_change_requests_school_id'), table_name='password_change_requests')
    op.drop_column('password_change_requests', 'school_id')
    # ### end Alembic commands ###
