"""add signup_requests table

Revision ID: 80adde15b397
Revises: a1b2ee1033bf
Create Date: 2026-02-21 16:29:55.173556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80adde15b397'
down_revision: Union[str, Sequence[str], None] = 'a1b2ee1033bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('requested_role', sa.Enum('student', 'teacher', name='signup_requested_role'), nullable=False),
    sa.Column('approved_role', sa.Enum('student', 'teacher', name='signup_approved_role'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='signup_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signup_requests_email'), 'signup_requests', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signup_requests_email'), table_name='signup_requests')
    op.drop_table('signup_requests')
    # ### end Alembic commands ###
