"""add description to assignments

Revision ID: a1b2ee1033bf
Revises: 06e62c2d30d8
Create Date: 2026-02-21 15:56:16.462323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2ee1033bf'
down_revision: Union[str, Sequence[str], None] = '06e62c2d30d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'description')
    # ### end Alembic commands ###
