from .user import User
from .teacher import Teacher
from .student import Student
from .course import Course
from .student_course import StudentCourse
from .teacher_course import TeacherCourse
from .learning_material import LearningMaterial
from .notes import Notes
from .assignment import Assignment
from .question import Question
from .mcq_option import MCQOption
from .student_assignment import StudentAssignment
from .student_answer import StudentAnswer
from .teacher_principal_consent import TeacherPrincipalConsent
