CREATE TABLE IF NOT EXISTS "users" (
	"Id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"Name" TEXT NOT NULL,
	"email" TEXT NOT NULL UNIQUE,
	"password_hash" TEXT NOT NULL,
	"role" ENUM(SUPER_ADMIN,PRINCIPAL,TEACHER,STUDENT) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("Id")
);




CREATE TABLE IF NOT EXISTS "teacher" (
	"user_id" INTEGER NOT NULL UNIQUE,
	"department" TEXT,
	"designation" TEXT,
	PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "student" (
	"user_id" INTEGER NOT NULL UNIQUE,
	"roll_number" INTEGER NOT NULL,
	"class" VARCHAR NOT NULL,
	PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "course" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT NOT NULL,
	"description" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "student_course" (
	"student_id" INTEGER NOT NULL,
	"course_id" INTEGER NOT NULL
);




CREATE TABLE IF NOT EXISTS "teacher_course" (
	"teacher_id" INTEGER NOT NULL,
	"course_id" INTEGER NOT NULL
);




CREATE TABLE IF NOT EXISTS "learning_material" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"course_id" INTEGER NOT NULL,
	"created_by_teacher_id" INTEGER NOT NULL,
	"title" TEXT NOT NULL,
	"type" ENUM(NOTES,ASSIGNMENT) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "notes" (
	"material_id" INTEGER NOT NULL UNIQUE,
	"content_url" TEXT NOT NULL,
	PRIMARY KEY("material_id")
);




CREATE TABLE IF NOT EXISTS "assignments" (
	"material_id" INTEGER NOT NULL UNIQUE,
	"assignment_type" ENUM(MCQ,LONG) NOT NULL,
	"total_marks" DECIMAL NOT NULL,
	"due_date" DATE NOT NULL,
	"max_attempts" INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY("material_id")
);




CREATE TABLE IF NOT EXISTS "questions" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"assignment_id" INTEGER NOT NULL,
	"question_text" TEXT NOT NULL,
	"question_type" ENUM(MCQ,LONG) NOT NULL,
	"marks" DECIMAL NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "mcq_options" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"question_id" INTEGER NOT NULL,
	"option_text" TEXT NOT NULL,
	"is_correct" BOOLEAN NOT NULL,
	"answers" TEXT NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "student_assignments" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"student_id" INTEGER NOT NULL,
	"assignment_id" INTEGER NOT NULL,
	"attempt_number" INTEGER NOT NULL,
	"submitted_at" TIMESTAMP,
	"total_score" DECIMAL,
	"status" ENUM(SUBMITTED,EVALUATED) NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "student_answers" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"student_assignment_id" INTEGER NOT NULL,
	"question_id" INTEGER NOT NULL,
	"answer_text" TEXT,
	"selected_option_id" INTEGER,
	"marks_obtained" DECIMAL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "teacher_principal_consent" (
	"teacher_id" INTEGER NOT NULL,
	"principal_id" INTEGER NOT NULL,
	"is_granted" BOOLEAN NOT NULL
);



ALTER TABLE "notes"
ADD FOREIGN KEY("material_id") REFERENCES "learning_material"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "teacher"
ADD FOREIGN KEY("user_id") REFERENCES "users"("Id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "student"
ADD FOREIGN KEY("user_id") REFERENCES "users"("Id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "assignments"
ADD FOREIGN KEY("material_id") REFERENCES "learning_material"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "questions"
ADD FOREIGN KEY("assignment_id") REFERENCES "assignments"("material_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "mcq_options"
ADD FOREIGN KEY("question_id") REFERENCES "questions"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "student_assignments"
ADD FOREIGN KEY("student_id") REFERENCES "users"("Id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "student_assignments"
ADD FOREIGN KEY("assignment_id") REFERENCES "assignments"("material_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "student_answers"
ADD FOREIGN KEY("student_assignment_id") REFERENCES "student_assignments"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "student_answers"
ADD FOREIGN KEY("question_id") REFERENCES "questions"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "student_answers"
ADD FOREIGN KEY("selected_option_id") REFERENCES "mcq_options"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "teacher_principal_consent"
ADD FOREIGN KEY("teacher_id") REFERENCES "users"("Id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "teacher_principal_consent"
ADD FOREIGN KEY("principal_id") REFERENCES "users"("Id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "student_course"
ADD FOREIGN KEY("student_id") REFERENCES "users"("Id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "student_course"
ADD FOREIGN KEY("course_id") REFERENCES "course"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "teacher_course"
ADD FOREIGN KEY("course_id") REFERENCES "course"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "teacher_course"
ADD FOREIGN KEY("teacher_id") REFERENCES "users"("Id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "learning_material"
ADD FOREIGN KEY("course_id") REFERENCES "course"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "learning_material"
ADD FOREIGN KEY("created_by_teacher_id") REFERENCES "users"("Id")
ON UPDATE NO ACTION ON DELETE NO ACTION;